### ISSUE TITLE
False positivies

### ISSUE THREAD

**Issue by Drug** [exec/sumac#1]
There are some false positives, what is causing them I have no idea. It may be just for me, since I have Tor on my browser, Skype, Pidgin, and a few other things. I'm running Windows 8.1 Pro x64, latest version of sumac, latest Tor (expert bundle) release. Out of the 23 availabilities the program returned, four were false.

**Comment by exec** [comment]
Yeah, blame Tor for having a faulty identity switch. If someone makes a fork of Tor and fixes it, or if the Tor Project devs fix it, I will be happy to get this issue resolved. If it's completely fixed I could bring the overall wait time between requests to <1 second... which would be nice.

In the mean time, try using a wordlist with taken names, modify the wait times, see how many false positives you get. If you find a perfect wait time, feel free to share it.

**Comment by exec** [comment]
Another option @drug would be to use a private socks5 proxy that revolves around multiple IPs to one server. I've been doing that for a while, you can just cut out any Tor code, remove importation of stem, etc. As far as I'm concerned this issue is resolved.
